#!/bin/bash
set -e
python runSimulation.py -e 0 --dams 1 --rand -a Lookup
python runSimulation.py -e 0 --dams 1 --rand -a Lookup
python runSimulation.py -e 0 --dams 1 --rand -a Lookup
python runSimulation.py -e 0 --dams 1 --rand -a Lookup
python runSimulation.py -e 0 --dams 1 --rand -a Lookup
python runSimulation.py -e 0 --dams 1 --rand -a Lookup
python runSimulation.py -e 0 --dams 1 --rand -a Lookup
python runSimulation.py -e 0 --dams 1 --rand -a Lookup
python runSimulation.py -e 0 --dams 1 --rand -a Lookup
python runSimulation.py -e 0 --dams 1 --rand -a Lookup
python runSimulation.py -e 0 --dams 1 --rand -a Lookup
python runSimulation.py -e 0 --dams 1 --rand -a Lookup
python runSimulation.py -e 0 --dams 1 --rand -a Lookup
python runSimulation.py -e 0 --dams 1 --rand -a Lookup
python runSimulation.py -e 0 --dams 1 --rand -a Lookup
python runSimulation.py -e 0 --dams 1 --rand -a Lookup
python runSimulation.py -e 0 --dams 1 --rand -a Lookup
python runSimulation.py -e 0 --dams 1 --rand -a Lookup
python runSimulation.py -e 0 --dams 1 --rand -a Lookup
python runSimulation.py -e 0 --dams 1 --rand -a Lookup
python runSimulation.py -e 0 --dams 1 --rand -a Lookup
python runSimulation.py -e 0 --dams 1 --rand -a Lookup
python runSimulation.py -e 0 --dams 1 --rand -a Lookup
python runSimulation.py -e 0 --dams 1 --rand -a Lookup
python runSimulation.py -e 0 --dams 1 --rand -a Lookup
python runSimulation.py -e 0 --dams 1 --rand -a Lookup
python runSimulation.py -e 0 --dams 1 --rand -a Lookup
python runSimulation.py -e 0 --dams 1 --rand -a Lookup
python runSimulation.py -e 0 --dams 1 --rand -a Lookup
python runSimulation.py -e 0 --dams 1 --rand -a Lookup
python runSimulation.py -e 0 --dams 1 --rand -a Lookup
python runSimulation.py -e 0 --dams 1 --rand -a Lookup
python runSimulation.py -e 0 --dams 1 --rand -a Lookup
python runSimulation.py -e 0 --dams 1 --rand -a Lookup
python runSimulation.py -e 0 --dams 1 --rand -a Lookup
python runSimulation.py -e 0 --dams 1 --rand -a Lookup
python runSimulation.py -e 0 --dams 1 --rand -a Lookup
python runSimulation.py -e 0 --dams 1 --rand -a Lookup
