
#rewards = read.csv('../model-control-chain/stats/rewards.txt', header=FALSE)
rewards = read.csv('~/memex/stats/rewards.txt', header=FALSE)

names(rewards) = c('reward1', 'reward2', 'elevation1', 'elevation2' )
par(mfrow=c(3,1))
#plot(tail(rollapply(rewards$reward,215,mean),10000), typ='l', xaxt='n')
plot(rewards$reward1, typ='l', xaxt='n')
lines(rewards$reward2, col='orange')
axis(1, at=215*(0:(ceiling(nrow(rewards) / 215))))
#plot(tail(rewards$elevation1,10000), typ='l', xaxt='n', ylim=c(205,240))
plot(rewards$elevation1, typ='l', xaxt='n', ylim=c(205,240))
axis(1, at=215*(0:(ceiling(nrow(rewards) / 215))))
abline(h=230,col='red')
abline(h=210,col='blue')
plot(rewards$elevation2, typ='l', xaxt='n', ylim=c(205,240))
axis(1, at=215*(0:(ceiling(nrow(rewards) / 215))))
abline(h=230,col='red')
abline(h=210,col='blue')
